export const GET_RATES = 'get_dealers_rates';
export const SET_INITIAL_VALUES = 'SET_INITIAL_VALUES';
export const UPDATE_PRODUCT_RATE = 'UPDATE_PRODUCT_RATE';
export const UPDATE_PRODUCT_RATE_COST = 'UPDATE_PRODUCT_RATE_COST';
export const UPDATE_RATE = 'UPDATE_RATE';
export const UPDATE_PLAN_PRICE = 'UPDATE_PLAN_PRICE';
